FROM ubuntu:18.04

ARG CSD_IP
ENV CSD_IP=$CSD_IP

ARG CSD_HOST_SERVER_IP
ENV CSD_HOST_SERVER_IP=$CSD_HOST_SERVER_IP

# 실행 파일을 컨테이너 내부로 복사
COPY csd-metric-collector-aarch64 /csd-metric-collector-aarch64

ENTRYPOINT ["/csd-metric-collector-aarch64"]