#define NUM_OF_BLOCKS 100
#define BUFFER_SIZE (NUM_OF_BLOCKS * 4096)
#define INPUT_IF_PORT 40301
#define CSD_WORKER_MODULE_HTTP_PORT 40302
#define PACKET_SIZE 36

#define T_SE_MERGING_TCP_PORT 40209

#define BUFF_M_PORT 40204
#define STORAGE_ENGINE_IP getenv("STORAGE_ENGINE_HOST_SERVER_IP")